services:
  mongo:
    image: mongo:7.0
    container_name: mongodb
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - urlshortner-network

  express:
    build:
      context: .
      dockerfile: Dockerfile
    image: urlshortner-app:latest
    container_name: url-shortner
    # restart: always
    ports:
      - "8000:8000" 
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      MONGO_URI: mongodb://root:password@mongo:27017/admin
    depends_on:
      - mongo
    networks:
      - urlshortner-network

volumes:
  mongo-data:

networks:
  urlshortner-network: